---
- name: Patch Windows VMs
  hosts: all
  gather_facts: no
  vars:
    ansible_shell_type: powershell
    ansible_shell_executable: powershell.exe
  tasks:
    - name: Ensure the latest updates are installed
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result

    - name: Log update results
      debug:
        msg: "{{ update_result }}"